[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags =
    -DLED_DATA_PIN=25
    -DNUM_LEDS=88
    -DHAS_HALL_SENSOR=1
    -DHALL_SENSOR_PIN=4
    -DARM_A_PIN=25
    -DARM_B_PIN=26
    -DCONFIG_BT_ENABLED=1
    -DCONFIG_BLUEDROID_ENABLED=1
lib_deps =
    fastled/FastLED @ ^3.7.0
    arduinojson @ ^7.2.0
    me-no-dev/ESP Async WebServer @ ^1.2.3
    ayushsharma22/ElegantOTA @ ^3.1.5
